gitlab:
  create:
    post:
      summary: Create GitLab Project
      description: |
        Create a new GitLab repository for a specific project.

        The GitLab parent namespace is calculated from the namespace configured in the parent Imbi group and the
        prefix configured in the project type.  If either value is not configured, then an error response is
        returned.
      tags:
        - Automations
      requestBody:
        description: Project details
        content:
          application/json:
            schema:
              type: object
              properties:
                project_id:
                  description: Imbi project ID to create the repository for
                  type: integer
              required:
                - project_id
      responses:
        '200':
          description: GitLab repository was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  gitlab_project_url:
                    type: string
                  gitlab_project_id:
                    type: integer
        '400':
          description: Request could not be processed

sentry:
  create:
    post:
      summary: Create Sentry Project
      description: Creates a new Sentry project using the info from the project.
      tags:
        - Automations
      requestBody:
        description: Project details
        content:
          application/json:
            schema:
              type: object
              properties:
                project_id:
                  description: Imbi project ID to create the Sonarqube Project for
                  type: integer
              required:
                - project_id
      responses:
        '200':
          description: Sentry project was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sentry_project_url:
                    type: string
                    format: url

sonarqube:
  create:
    post:
      summary: Create Sonarqube Project
      description: |
        Creates a new Sonarqube project using info from the project, including the GitLab Project ID.
      tags:
        - Automations
      requestBody:
        description: Project details
        content:
          application/json:
            schema:
              type: object
              properties:
                project_id:
                  description: Imbi project ID to create the Sonarqube Project for
                  type: integer
              required:
                - project_id
      responses:
        '200':
          description: Sonarqube project was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sonarqube_dashboard:
                    type: string
                    format: url
                  sonarqube_project_key:
                    type: string
        '400':
          description: Request could not be processed
