paths:
  collection:
    parameters:
      - name: id
        in: path
        description: ID of the project to get parameters for
        required: true
        schema:
          type: number
    get:
      description: Retrieve the SSM parameters for the project
      summary: Get SSM Parameters
      tags: [Project Configuration]
      responses:
        '200':
          description: Success
          content:
            application/json: &collectionResponse
              schema:
                $ref: '../schemas/project_configuration_ssm.yaml#/read'
              examples:
                records:
                  value:
                    - name: "/foo/bar/baz"
                      type: String
                      values:
                        - environment: Testing
                          value: "42"
                        - environment: Production
                          value: "9001"
                    - name: "biz/bap/boop"
                      type: SecureString
                      values:
                        - environment: Testing
                          value: "password"
                        - environment: Production
                          value: "password123$"
            application/msgpack:
              <<: *collectionResponse
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
        '404': { $ref: '../components/responses.yaml#/NotFound' }
