paths:
  collection:
    parameters:
      - name: id
        in: path
        description: ID of the project to get parameters for
        required: true
        schema:
          type: number
    get:
      description: Retrieve the SSM parameters for the project
      summary: Get SSM Parameters
      tags: [Project Configuration]
      responses:
        '200':
          description: Success
          content:
            application/json: &collectionResponse
              schema:
                $ref: '../schemas/project_configuration_ssm.yaml#/read'
              examples:
                records:
                  value:
                    - name: "/foo/bar/baz"
                      values:
                        - environment: Testing
                          value: "42"
                          type: String
                        - environment: Production
                          value: "9001"
                          type: String
                    - name: "biz/bap/boop"
                      values:
                        - environment: Testing
                          value: "password"
                          type: SecureString
                        - environment: Production
                          value: "password123$"
                          type: SecureString
            application/msgpack:
              <<: *collectionResponse
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
        '404': { $ref: '../components/responses.yaml#/NotFound' }
    post:
      description: Create a set of new SSM parameters for a name
      summary: Create SSM params
      tags: [Project Configuration]
      requestBody:
        description: Parameters to create
        content:
          application/json: &postResponse
            schema:
              $ref: '../schemas/project_configuration_ssm.yaml#/write'
            example:
              name: "foo/bar/baz"
              type: String
              values:
                Testing: "42"
                Production: "9001"
          application/msgpack:
             <<: *postResponse
      responses:
        '204':
          description: The request to add SSM parameters was successful
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
