paths:
  collection:
    parameters:
      - name: id
        in: path
        description: ID of the project to get parameters for
        required: true
        schema:
          type: number
    get:
      description: Retrieve the SSM parameters for the project
      summary: Get SSM Parameters
      tags: [Project Configuration]
      responses:
        '200':
          description: Success
          content:
            application/json: &collectionResponse
              schema:
                $ref: '../schemas/project_configuration_ssm.yaml#/read'
              examples:
                records:
                  value:
                    - name: "foo/bar/baz"
                      values:
                        Testing:
                          value: "42"
                          type: String
                        Production:
                          value: "9001"
                          type: String
                      self: "https://imbi.com/project/3/configuration/ssm/foo%2Fbar%2Fbaz"
                    - name: "biz/bap/boop"
                      values:
                        Testing:
                          value: "password"
                          type: SecureString
                        Production:
                          value: "password123$"
                          type: SecureString
                      self: "https://imbi.com/project/3/configuration/ssm/biz%2Fbap%2Fboop"
            application/msgpack:
              <<: *collectionResponse
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
        '404': { $ref: '../components/responses.yaml#/NotFound' }
    post:
      description: Create a set of new SSM parameters for a name
      summary: Create SSM params
      tags: [Project Configuration]
      requestBody:
        description: Parameters to create
        content:
          application/json: &postBody
            schema:
              $ref: '../schemas/project_configuration_ssm.yaml#/write'
            example:
              name: "foo/bar/baz"
              type: String
              values:
                Testing: "42"
                Production: "9001"
          application/msgpack:
             <<: *postBody
      responses:
        '204':
          description: The request to add SSM parameters was successful
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
    delete:
      summary: Delete a set of SSM parameters
      description: Delete SSM params
      tags: [ Project Configuration ]
      requestBody:
        description: Parameters to delete
        content:
          application/json: &deleteBody
            schema:
              $ref: '../schemas/project_configuration_ssm.yaml#/delete'
            example:
              name: "foo/bar/baz"
              environments:
                - Testing
                - Production
          application/msgpack:
            <<: *deleteBody
      responses:
        '204': { $ref: '../components/responses.yaml#/RecordRemoved' }
        '401': { $ref: '../components/responses.yaml#/Unauthorized' }
        '404': { $ref: '../components/responses.yaml#/NotFound' }
