read:
  title: Project SSM Configuration
  description: SSM parameters for the project
  type: array
  items:
    description: The SSM parameter
    type: object
    properties:
      name:
        description: The SSM parameter path
        type: string
      type:
        description: The SSM parameter type
        type: string
        enum:
          - String
          - SecureString
          - StringList
      values:
        description: The parameter values in each environment
        type: array
        items:
          description: The parameter value in this environment
          type: object
          properties:
            environment:
              description: The environment the parameter exists in
              type: string
            value:
              description: The parameter value
              type: string
          additionalProperties: false
          required:
            - environment
            - value
    additionalProperties: false
    required:
      - name
      - type
      - values
