read:
  title: Project SSM Configuration
  description: SSM parameters for the project
  type: array
  items:
    description: The SSM parameter
    type: object
    properties:
      name:
        description: The SSM parameter path
        type: string
      values:
        description: The parameter values in each environment
        type: object
        additionalProperties:
          type: object
          properties:
            value:
              description: The parameter value
              type: string
            type: &type
              description: The SSM parameter type
              type: string
              enum:
                - String
                - SecureString
                - StringList
          additionalProperties: false
          required:
            - value
            - type
      self:
        description: URL referring to this parameter for this project, with SSM name URL-encoded
        type: string
    additionalProperties: false
    required:
      - self
      - name
      - values

write:
  title: Project SSM Configuration
  description: SSM parameters for a given name
  type: object
  properties:
    name:
      description: The SSM parameter path after the project prefix
      type: string
    type:
      <<: *type
    values:
      description: The parameter values in each environment
      type: object
      additionalProperties:
        type: string
  additionalProperties: false
  required:
    - name
    - type
    - values

delete:
  title: Project SSM Configuration
  description: SSM parameters for a given name
  type: object
  properties:
    name:
      description: The SSM parameter path after the project prefix
      type: string
    environments:
      type: array
      items:
        description: Environments to delete this parameter in
        type: string
  additionalProperties: false
  required:
    - name
    - environments
