read:
  title: Project
  description: Describes a project managed by Imbi
  type: object
  properties:
    id:
      description: The project ID
      type: number
    created_by:
      description: The user that created the record
      type: string
    last_modified_by:
      description: The user that last modified the record
      type: string
    namespace_id:
      description: The project namespace ID
      type: number
    namespace:
      description: The namespace name
      type: string
    project_type_id:
      description: The project type ID
      type: number
    project_type:
      description: The project type name
      type: string
    name:
      description: The project name
      type: string
    slug:
      description: The project URL slug (In GitLab and other projects)
      type: string
      pattern: ^[\w-]+$
    description:
      description: Long for description of the project
      type: string
      nullable: true
    environments:
      description: The operational environments the project is available in
      type: array
      items:
        type: string
      nullable: true
    archived:
      description: Indicates that the project is archived
      type: boolean
    gitlab_project_id:
      description: Optional project ID for the associated gitlab project
      type: integer
      nullable: true
    sentry_project_slug:
      description: Optional slug for the project in sentry
      type: string
      nullable: true
    sonarqube_project_key:
      description: Optional slug for the project in SonarQube
      type: string
      nullable: true
    pagerduty_service_id:
      description: Optional ID for the project in PagerDuty
      type: string
      nullable: true
  additionalProperties: false

write:
  title: Project
  description: Describes a project managed by Imbi
  type: object
  properties:
    namespace_id:
      description: The project namespace ID
      type: number
    project_type_id:
      description: The project type ID
      type: number
    name:
      description: The project name
      type: string
    slug:
      description: The project URL slug (In GitLab and other projects)
      type: string
      pattern: ^[\w-]+$
    description:
      description: Long for description of the project
      type: string
      nullable: true
    environments:
      description: The operational environments the project is available in
      type: array
      items:
        type: string
      minLength: 1
      nullable: true
  required:
    - namespace_id
    - project_type_id
    - name
    - slug
  additionalProperties: false
