openapi: 3.0.3

info:
  title: Imbi
  description: |-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: '{{ settings["version"] }}'
  contact:
    name: AWeber
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

components:
  securitySchemes:
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session
    token:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token

security:
  - session: []
  - token: []

paths:
  /activity-feed: { $ref: 'endpoints/activity_feed.yaml#/paths/collection' }
  /authentication-tokens:
    { $ref: 'endpoints/authentication_tokens.yaml#/paths/collection' }
  /authentication-tokens/{token}:
    { $ref: 'endpoints/authentication_tokens.yaml#/paths/manage' }
  /aws-roles: { $ref: 'endpoints/aws_role.yaml#/paths/collection' }
  /aws-roles/{id}: { $ref: 'endpoints/aws_role.yaml#/paths/manage' }
  /components: { $ref: 'endpoints/components.yaml#/paths/collection' }
  /components/{package_url}: { $ref: 'endpoints/components.yaml#/paths/manage' }
  /cookie-cutters: { $ref: 'endpoints/cookie_cutter.yaml#/paths/collection' }
  /cookie-cutters/{name}: { $ref: 'endpoints/cookie_cutter.yaml#/paths/manage' }
  /environments: { $ref: 'endpoints/environment.yaml#/paths/collection' }
  /environments/{name}: { $ref: 'endpoints/environment.yaml#/paths/manage' }
  /gitlab/auth: { $ref: 'endpoints/gitlab.yaml#/paths/auth' }
  /gitlab/namespaces: { $ref: 'endpoints/gitlab.yaml#/paths/namespaces' }
  /gitlab/projects: { $ref: 'endpoints/gitlab.yaml#/paths/projects' }
  /groups: { $ref: 'endpoints/group.yaml#/paths/collection' }
  /groups/{name}: { $ref: 'endpoints/group.yaml#/paths/manage' }
  /metrics: { $ref: 'endpoints/metrics.yaml#/paths/metrics' }
  /namespaces: { $ref: 'endpoints/namespace.yaml#/paths/collection' }
  /namespaces/{id}: { $ref: 'endpoints/namespace.yaml#/paths/manage' }
  /integrations: { $ref: 'endpoints/integrations.yaml#/paths/collection' }
  /integrations/{name}: { $ref: 'endpoints/integrations.yaml#/paths/manage' }
  /integrations/{integration_name}/automations:
    { $ref: 'endpoints/automations.yaml#/paths/collection'}
  /integrations/{integration_name}/automations/{automation_name}:
    { $ref: 'endpoints/automations.yaml#/paths/manage'}
  /integrations/{integration_name}/notifications:
    { $ref: 'endpoints/integration_notifications.yaml#/paths/collection' }
  /integrations/{integration_name}/notifications/{notification_name}:
    { $ref: 'endpoints/integration_notifications.yaml#/paths/manage' }
  /integrations/{integration_name}/notifications/{notification_name}/filters:
    { $ref: 'endpoints/notification_filters.yaml#/paths/collection' }
  /integrations/{integration_name}/notifications/{notification_name}/filters/{filter_name}:
    { $ref: 'endpoints/notification_filters.yaml#/paths/manage' }
  /integrations/{integration_name}/notifications/{notification_name}/rules:
    { $ref: 'endpoints/notification_rules.yaml#/paths/collection' }
  /integrations/{integration_name}/notifications/{notification_name}/rules/{rule_name}:
    { $ref: 'endpoints/notification_rules.yaml#/paths/manage' }
  /integrations/{integration_name}/notifications/{notification_name}/rules/{fact_type_id}/transformations:
    { $ref: 'endpoints/notification_rule_transformations.yaml#/paths/collection' }
  /integrations/{integration_name}/notifications/{notification_name}/rules/{fact_type_id}/transformations/{id}:
    { $ref: 'endpoints/notification_rule_transformations.yaml#/paths/manage' }
  /operations-log: { '$ref': 'endpoints/operations_log.yaml#/paths/collection' }
  /operations-log/{id}:
    { '$ref': 'endpoints/operations_log.yaml#/paths/manage' }
  /operations-log/build-search-index:
    { '$ref': 'endpoints/operations_log.yaml#/paths/search'}
  /permissions: { $ref: 'endpoints/permissions.yaml#/paths/collection' }
  /project-fact-types:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/collection' }
  /project-fact-types/{fact_type_id}:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/manage' }
  /project-fact-type-enums:
    { $ref: 'endpoints/project_fact_type_enum.yaml#/paths/collection' }
  /project-fact-type-enums/{id}:
    { $ref: 'endpoints/project_fact_type_enum.yaml#/paths/manage' }
  /project-fact-type-ranges:
    { $ref: 'endpoints/project_fact_type_range.yaml#/paths/collection' }
  /project-fact-type-ranges/{id}:
    { $ref: 'endpoints/project_fact_type_range.yaml#/paths/manage' }
  /project-link-types:
    { $ref: 'endpoints/project_link_type.yaml#/paths/collection' }
  /project-link-types/{id}:
    { $ref: 'endpoints/project_link_type.yaml#/paths/manage' }
  /project-types: { $ref: 'endpoints/project_type.yaml#/paths/collection' }
  /project-types/{id}: { $ref: 'endpoints/project_type.yaml#/paths/manage' }
  /projects: { '$ref': 'endpoints/projects.yaml#/paths/collection' }
  /projects/{id}: { '$ref': 'endpoints/projects.yaml#/paths/manage' }
  /projects/{id}/components:
    { '$ref': 'endpoints/project_components.yaml#/paths/collection' }
  /projects/{id}/configuration/ssm:
    { '$ref': 'endpoints/project_configuration_ssm.yaml#/paths/collection' }
  /projects/{id}/configuration/ssm/{name}:
    { '$ref': 'endpoints/project_configuration_ssm.yaml#/paths/record' }
  /projects/{id}/facts:
    { '$ref': 'endpoints/project_facts.yaml#/paths/collection' }
  /projects/{id}/fact-types:
    { '$ref': 'endpoints/project_fact_types.yaml#/paths/collection' }
  /projects/{id}/fact-history:
    { '$ref': 'endpoints/project_fact_history.yaml#/paths/collection'}
  /projects/{id}/feed:
    { '$ref': 'endpoints/project_activity_feed.yaml#/paths/collection' }
  /projects/{id}/identifiers:
    { '$ref': 'endpoints/project_identifiers.yaml#/paths/collection'}
  /projects/{id}/identifiers/{integration}:
    { '$ref': 'endpoints/project_identifiers.yaml#/paths/entry'}
  /projects/{id}/links:
    { '$ref': 'endpoints/project_links.yaml#/paths/collection' }
  /projects/{id}/links/{link_type_id}:
    { '$ref': 'endpoints/project_links.yaml#/paths/manage' }
  /projects/{id}/notes:
    { '$ref': 'endpoints/project_notes.yaml#/paths/collection' }
  /projects/{id}/notes/{note_id}:
    { '$ref': 'endpoints/project_notes.yaml#/paths/manage' }
  /projects/{id}/dependencies:
    { '$ref': 'endpoints/project_dependencies.yaml#/paths/collection' }
  /projects/{id}/dependencies/{dependency_id}:
    { '$ref': 'endpoints/project_dependencies.yaml#/paths/manage' }
  /projects/{id}/sbom:
    { $ref: 'endpoints/project_sbom.yaml#/paths/collection' }
  /projects/{id}/secrets:
    { $ref: 'endpoints/project_secrets.yaml#/paths/collection' }
  /projects/{id}/score-detail:
    { '$ref': 'endpoints/project_score_detail.yaml#/paths' }
  /projects/{id}/score-history:
    { '$ref': 'endpoints/project_score_history.yaml#/paths/collection' }
  /projects/{id}/urls:
    { '$ref': 'endpoints/project_urls.yaml#/paths/collection' }
  /projects/{id}/urls/{environment}:
    { '$ref': 'endpoints/project_urls.yaml#/paths/manage' }
  /projects/build-search-index:
    { '$ref': 'endpoints/projects.yaml#/paths/search' }
  /reports/component-usage:
    { $ref: 'endpoints/component_usage_report.yaml#/paths/collection' }
  /reports/namespace-shs-history:
    { $ref: 'endpoints/namespace_shs_history.yaml#/paths/collection' }
  /reports/system-shs-history:
    { $ref: 'endpoints/system_shs_history.yaml#/paths/collection' }
  /status: { $ref: 'endpoints/status.yaml#/paths/status' }
  /ui/automations/gitlab/create:
    { $ref: 'endpoints/automations.yaml#/gitlab/create' }
  /ui/automations/sentry/create:
    { $ref: 'endpoints/automations.yaml#/sentry/create' }

tags:
  - name: Activity Feed
    description: Endpoints that detail changes to projects and other entities in Imbi
  - name: Automations
    description: Endpoints related to project automations
  - name: Components
    description: Endpoints for managing components and their usage in projects
  - name: Cookie Cutters
    description: Endpoints used for the management of project creation cookie cutters
  - name: Environments
    description: Endpoints used for the management different target environments for projects to run in.
  - name: Groups
    description: |-
      Endpoints used to manage the groups that Imbi users are able to be members of.
  - name: Namespaces
    description: Endpoints used for the management of organizational namespaces
  - name: Fact Types
    description: |-
      Management of records that define types facts that may be collected for a project.

      Project facts may be used to calculate a current project health score. For more
      information on project health score, see the compliance documentation.
    x-displayName: Project Fact Types
  - name: Fact Type Enums
    description: |-
      Management of records that define enum values for different fact types that may be collected for a project.

      Project facts enums provide the possible values for project facts, and are
      used to compute the score of that project fact. For more information on
      project health score, see the compliance documentation.
    x-displayName: Project Fact Type Enums
  - name: Fact Type Ranges
    description: |-
      Management of records that define range values for different fact types that
      may be collected for a project.

      Project facts ranges provide the possible range values for project facts, and
      are used to compute the score of that project fact. For more information on
      project health score, see the compliance documentation.
    x-displayName: Project Fact Type Ranges
  - name: Project Link Types
    description: |-
      Management of records that define types of links or URLs to associate with a project
  - name: Project Types
    description: Endpoints used for the management different types of projects managed in Imbi (APIs, Databases, etc)
  - name: Projects
    description: Endpoints used for the management of projects
  - name: Project Activity Feed
    description: Endpoints that detail activity on a project
  - name: Project Configuration
    description: Endpoints to manage project configuration
  - name: Project Dependencies
    description: Endpoints used to manage the relationships of projects to other projects
  - name: Project Facts
    description: Endpoints for managing the current facts describing the project
  - name: Project Fact Types
    description: An endpoint for returning the project fact types for a specific project
  - name: Project Fact History
    description: Endpoint for returning the project fact history for a specific project
  - name: Project Links
    description: Endpoints used to manage links to external resources for a project
  - name: Project Notes
    description: Endpoints used to manage notes for a project
  - name: Project Scores
    description: Endpoints detailing information about project scores
  - name: Project URLs
    description: Endpoints used to manage urls to the project in each operational environment
  - name: Operations Log
    description: Endpoints used for created, querying, and managing entries in the Operations Log
  - name: Reports
    description: Endpoints used to report on the state of various objects in Imbi
  - name: Settings
    description: Endpoints used for retrieving settings for the Imbi UI
  - name: Integrations
    description: Endpoints used to retrieve information about applications that Imbi is integrated with
  - name: Notifications
    description: Endpoints used for integrating Imbi with webhooks from other applications
  - name: Monitoring & Metrics
    description: |-
      Endpoints used for health checking, service status, and service metrics
  - name: User
    description: Endpoints related to the current user

x-tagGroups:
  - name: Activity Feed
    tags:
      - Activity Feed
      - Project Activity Feed
  - name: Administration
    tags:
      - Groups
      - Users
  - name: Metadata
    tags:
      - Cookie Cutters
      - Environments
      - Namespaces
      - Fact Types
      - Fact Type Enums
      - Fact Type Ranges
      - Project Link Types
      - Project Types
  - name: Integrations
    tags:
      - Integrations
      - Notifications
      - Automations
  - name: Operations Log
    tags:
      - Operations Log
  - name: Project Management
    tags:
      - Components
      - Projects
      - Project Configuration
      - Project Dependencies
      - Project Facts
      - Project Fact Types
      - Project Fact History
      - Project Links
      - Project Notes
      - Project Scores
      - Project URLs
  - name: Reports
    tags:
      - Reports
  - name: Current User
    tags:
      - User
  - name: UI Specific
    tags:
      - Dashboard
      - Settings
  - name: Other
    tags:
      - Monitoring & Metrics
